name: gloves
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - ca-certificates=2020.12.8=h06a4308_0
  - certifi=2020.12.5=py36h06a4308_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - ncurses=6.2=he6710b0_1
  - openssl=1.1.1i=h27cfd23_0
  - pip=20.3.3=py36h06a4308_0
  - python=3.6.12=hcff3b4d_2
  - readline=8.0=h7b6447c_0
  - setuptools=51.3.3=py36h06a4308_4
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.10=hbc83047_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - absl-py==0.11.0
    - alembic==1.4.1
    - altair==4.1.0
    - appdirs==1.4.4
    - argon2-cffi==20.1.0
    - astor==0.8.1
    - astunparse==1.6.3
    - async-generator==1.10
    - atpublic==2.1.2
    - attrs==20.3.0
    - azure-core==1.10.0
    - azure-storage-blob==12.7.1
    - backcall==0.2.0
    - base58==2.1.0
    - bleach==3.2.2
    - blinker==1.4
    - boto3==1.16.57
    - botocore==1.19.57
    - cachetools==4.2.0
    - cffi==1.14.4
    - chardet==4.0.0
    - click==7.1.2
    - cloudpickle==1.6.0
    - colorama==0.4.4
    - commonmark==0.9.1
    - configobj==5.0.6
    - cryptography==3.3.1
    - databricks-cli==0.14.1
    - dataclasses==0.7
    - decorator==4.4.2
    - defusedxml==0.6.0
    - dictdiffer==0.8.1
    - distro==1.5.0
    - docker==4.4.1
    - dpath==2.0.1
    - dulwich==0.20.15
    - dvc==1.11.10
    - entrypoints==0.3
    - flask==1.1.2
    - flatbuffers==1.12
    - flatten-dict==0.3.0
    - flufl-lock==3.2
    - ftfy==5.8
    - funcy==1.15
    - future==0.18.2
    - gast==0.3.3
    - gitdb==4.0.5
    - gitpython==3.1.12
    - google-auth==1.24.0
    - google-auth-oauthlib==0.4.2
    - google-pasta==0.2.0
    - grandalf==0.6
    - grpcio==1.32.0
    - gunicorn==20.0.4
    - h5py==2.10.0
    - idna==2.10
    - importlib-metadata==3.4.0
    - ipykernel==5.4.3
    - ipython==7.16.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.3
    - isodate==0.6.0
    - itsdangerous==1.1.0
    - jedi==0.18.0
    - jinja2==2.11.2
    - jmespath==0.10.0
    - jsonpath-ng==1.5.2
    - jsonschema==3.2.0
    - jupyter-client==6.1.11
    - jupyter-core==4.7.0
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.0
    - keras-preprocessing==1.1.2
    - mailchecker==4.0.3
    - mako==1.1.4
    - markdown==3.3.3
    - markupsafe==1.1.1
    - mistune==0.8.4
    - mlflow==1.13.1
    - msrest==0.6.19
    - nanotime==0.5.2
    - nbclient==0.5.1
    - nbconvert==6.0.7
    - nbformat==5.1.2
    - nest-asyncio==1.4.3
    - networkx==2.5
    - notebook==6.2.0
    - numpy==1.19.5
    - oauthlib==3.1.0
    - opt-einsum==3.3.0
    - packaging==20.8
    - pandas==1.1.5
    - pandocfilters==1.4.3
    - parso==0.8.1
    - pathlib2==2.3.5
    - pathspec==0.8.1
    - pexpect==4.8.0
    - phonenumbers==8.12.16
    - pickleshare==0.7.5
    - pillow==8.1.0
    - ply==3.11
    - prometheus-client==0.9.0
    - prometheus-flask-exporter==0.18.1
    - prompt-toolkit==3.0.11
    - protobuf==3.14.0
    - ptyprocess==0.7.0
    - pyarrow==2.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.20
    - pydeck==0.5.0
    - pydot==1.4.1
    - pygments==2.7.4
    - pygtrie==2.3.2
    - pyparsing==2.4.7
    - pyrsistent==0.17.3
    - python-benedict==0.23.2
    - python-dateutil==2.8.1
    - python-editor==1.0.4
    - python-fsutil==0.4.0
    - python-slugify==4.0.1
    - pytz==2020.5
    - pyyaml==5.4
    - pyzmq==21.0.1
    - querystring-parser==1.2.4
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - rich==9.8.2
    - rsa==4.7
    - ruamel-yaml==0.16.12
    - ruamel-yaml-clib==0.2.2
    - s3transfer==0.3.4
    - send2trash==1.5.0
    - shortuuid==1.0.1
    - shtab==1.3.4
    - six==1.15.0
    - smmap==3.0.4
    - sqlalchemy==1.3.22
    - sqlparse==0.4.1
    - streamlit==0.74.1
    - tabulate==0.8.7
    - tensorboard==2.4.1
    - tensorboard-plugin-wit==1.8.0
    - tensorflow-estimator==2.4.0
    - tensorflow-gpu==2.4.0
    - termcolor==1.1.0
    - terminado==0.9.2
    - testpath==0.4.4
    - text-unidecode==1.3
    - toml==0.10.2
    - toolz==0.11.1
    - tornado==6.1
    - tqdm==4.56.0
    - traitlets==4.3.3
    - typing-extensions==3.7.4.3
    - tzlocal==2.1
    - urllib3==1.26.2
    - validators==0.18.2
    - voluptuous==0.12.1
    - watchdog==1.0.2
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==0.57.0
    - werkzeug==1.0.1
    - widgetsnbextension==3.5.1
    - wrapt==1.12.1
    - xmltodict==0.12.0
    - zc-lockfile==2.0
    - zipp==3.4.0
